In [1]:
%matplotlib widget

from openbb import obb
import matplotlib.pyplot as plt
import mplcursors
import numpy as np
import pandas as pd

import re

Retrieve a list of ETFs and mutual funds. Previous searches on web-based market information platforms lead me to believe that between the US and Canada, I should expect about 10,000 records.

However, the US and GB results are not what I expected. Let's focus on the Canadian results.

Reference: https://docs.openbb.co/odp/python/reference/tmx/equity/search.

In [37]:
#tmx_indices = obb.tmx.index.available(provider='tmx').to_dataframe()
#tmx_etfs = obb.tmx.etf.search(provider='tmx').to_dataframe()
tmx_funds_CA = obb.tmx.equity.search(query='', provider='tmx', country='CA', limit=1e6).to_dataframe()
tmx_funds_US = obb.tmx.equity.search(query='', provider='tmx', country='US', limit=1e6).to_dataframe()
tmx_funds_GB = obb.tmx.equity.search(query='', provider='tmx', country='GB', limit=1e6).to_dataframe()
display(tmx_funds_CA)
display(tmx_funds_US)
display(tmx_funds_GB)

,symbol,name,exchange,exchange_code,country,security_type,market_cap,optionable
0,NVDA,Nvidia CDR (CAD Hedged),TSX,TSX,CA,Equity,7.582715e+12,True
1,AAPL,Apple CDR (CAD Hedged),TSX,TSX,CA,Equity,7.116222e+12,True
2,GOOG,Alphabet CDR (CAD Hedged),TSX,TSX,CA,Equity,6.044808e+12,True
3,MSFT,Microsoft CDR (CAD Hedged),TSX,TSX,CA,Equity,5.634349e+12,True
4,AMZN,Amazon.com CDR (CAD Hedged),TSX,TSX,CA,Equity,3.896456e+12,True
...,...,...,...,...,...,...,...,...
101445,IGI1551,IG Managed Growth Portfolio - Global Equity Se...,CMF,CMF,CA,Mutual Fund,0.000000e+00,False
101446,IGI1552,IG Managed Growth Portfolio - Global Equity Se...,CMF,CMF,CA,Mutual Fund,0.000000e+00,False
101447,IGI1458,IG Core Portfolio - Income Focus Series J-RDSP,CMF,CMF,CA,Mutual Fund,0.000000e+00,False
101448,IGI1459,IG Core Portfolio - Income Focus Series C,CMF,CMF,CA,Mutual Fund,0.000000e+00,False
101449,CSH30272,ACCINS MMB lnk Amer Mkt F NC3Y PWM 032432,CMF,CMF,CA,Mutual Fund,0.000000e+00,False

,symbol,name,exchange,exchange_code,country,security_type,market_cap,optionable
0,^OMXSPI,OMX Stockholm_PI,NSD,GIDS,US,Index,0.0,False
1,^OMXC20,OMX Copenhagen 20,NSD,GIDS,US,Index,0.0,False
2,^OMXS30,OMX Stockholm 30 Index,NSD,GIDS,US,Index,0.0,False
3,^OMXH25,OMX Helsinki 25,NSD,GIDS,US,Index,0.0,False

,symbol,name,exchange,exchange_code,country,security_type,market_cap,optionable
0,$EURYLV,EU Euro - Crypto.com Chain,FOREX,FRXL,GB,Forex,0.0,False
1,$YLRWFX,Ankr Network - Binance USD,FOREX,FRXL,GB,Forex,0.0,False
2,$YWSXEH,PAX Gold - Ethereum,FOREX,FRXL,GB,Forex,0.0,False
3,$YSGZAR,Cosmos - South Africa Rand,FOREX,FRXL,GB,Forex,0.0,False
4,$YLPXUD,Blur - Tether,FOREX,FRXL,GB,Forex,0.0,False
...,...,...,...,...,...,...,...,...
13747,$USDVBR,USA Dollars - VBR,FOREX,FRXL,GB,Forex,0.0,False
13748,$USDVBU,USA Dollars - VBU,FOREX,FRXL,GB,Forex,0.0,False
13749,$USDVBT,USA Dollars - VBT,FOREX,FRXL,GB,Forex,0.0,False
13750,$USDVBW,USA Dollars - VBW,FOREX,FRXL,GB,Forex,0.0,False
13751,$XZEYER,Zcash - Yemen Rials,FOREX,FRXL,GB,Forex,0.0,False

In [40]:
display(tmx_funds_CA['security_type'].value_counts())

security_type
Mutual Fund          95385
Equity                3010
ETF                   1873
Future                 454
Money Market Fund      449
Index                  279
Name: count, dtype: int64

I did not expect so many mutual funds! Let's find the largest ETF and mutual fund by market capitalization and retrieve more detailed information about it.

In [44]:
display(tmx_funds_CA[tmx_funds_CA['security_type'].isin(['Mutual Fund'])].sort_values(by=['market_cap','symbol'],ascending=False).head(5))
display(tmx_funds_CA[tmx_funds_CA['security_type'].isin(['ETF'])].sort_values(by=['market_cap','symbol'],ascending=False).head(5))

,symbol,name,exchange,exchange_code,country,security_type,market_cap,optionable
436,MAW220,Mawer Global Equity Fund Series O,CMF,CMF,CA,Mutual Fund,1.308564e+10,False
456,TDB886,TD Comfort Balanced Portfolio Inv,CMF,CMF,CA,Mutual Fund,1.115240e+10,False
471,TDB887,TD Comfort Balanced Growth Portfolio Inv,CMF,CMF,CA,Mutual Fund,1.028465e+10,False
482,MAW202,Mawer International Equity Fund Series O,CMF,CMF,CA,Mutual Fund,9.603928e+09,False
488,BMO70146,BMO Dividend Fund Series A,CMF,CMF,CA,Mutual Fund,8.957073e+09,False

,symbol,name,exchange,exchange_code,country,security_type,market_cap,optionable
31,LRCX,Lam Research CDR (CAD Hedged),TSX,TSX,CA,ETF,5.104953e+11,False
43,SAPS,SAP CDR (CAD Hedged),TSX,TSX,CA,ETF,3.851163e+11,False
54,KLAC,KLA CDR (CAD Hedged),TSX,TSX,CA,ETF,3.317652e+11,False
57,MRV,Marvell Technology CDR (CAD Hedged),TSX,TSX,CA,ETF,3.058007e+11,False
61,SNDK,Sandisk CDR (CAD Hedged),TSX,TSX,CA,ETF,2.899596e+11,False

In [45]:
display(tmx_funds_CA[tmx_funds_CA['symbol'].isin(['VEQT'])].sort_values(by=['market_cap','symbol'],ascending=False).head(5))

,symbol,name,exchange,exchange_code,country,security_type,market_cap,optionable
398,VEQT,Vanguard All-Equity ETF Portfolio,TSX,TSX,CA,ETF,1.773603e+10,False